### ISSUE TITLE
Question about the buttons in each card should be aligned 

### ISSUE THREAD

**Issue by nguy1072** [nguy1072/mtm6201-week2#1]
Dear Professor @kaura5, 

I have tried many scenarios when it comes to making the button have the same alignment at the bottom of the cards. For emoji a section, I used flex-wrap: wrap, and justify-content: flex-end but still nothing changed. I would be so happy to get your advice or hint on what things did I do wrong in this case. 

Thank you so much, and I appreciate your support a lot. 

All the best,
Lyn 
<img width="423" alt="Problems with the buttons alignment" src="https://github.com/nguy1072/mtm6201-week2/assets/144856689/a7acceb0-e9b1-40c4-a130-13528defc98d">

**Comment by kaura5** [comment]
Hello @nguy1072 ,

justify-content: space-between on flex-container will push the items to the flex start and flex end.

Give that a try.
Anoop
